theme: minima
title: My awesome title
author: tbfaust
email: your-email@domain.com
description: Be kind, I'm new here.

# social links
twitter_username: tbfaust # DO NOT include the @ character, or else the build will fail!
github_username: tbfaust # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
